language: rust

before_install:
 - sudo add-apt-repository --yes "ppa:codegear/release"
 - sudo apt-get-repository --yes "ppa:keithw/glfw3"
 - sudo apt-get update -qq
 - sudo apt-get -qq --yes install premake4
 - sudo apt-get -qq --yes install glfw3

os:
- linux
- osx

install:
- sudo apt-get install libXxf86vm-dev libosmesa6-dev

script:
- cargo build --verbose
- cargo test --verbose
- cargo doc --verbose

after_success: |
   [ $TRAVIS_BRANCH = master ] &&
   [ $TRAVIS_PULL_REQUEST = false ] &&
   cargo doc &&
   echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
   sudo pip install ghp-import &&
   ghp-import -n target/doc &&
   git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
    secure: Vu3dOn4Dme5L0qeofxBdgSbKoCoR9SMWUe/1/lIRQZ2DebJW7kzVQ8oqWQExNUe+Ci74/13Zv1cMA0RhPc79oGasPxpqvdJ5q1Zo4hSrPAne4MU59NVmyDx1eXZGvbvsdprYX+VX9gqvKH6329OimkMc9qJTI7vkBs76ZbuTopE=
