[package]
name = "rui"
version = "0.0.0"
repository = "https://github.com/enex/rust-gui.git"
license = "LGPL"
authors = ["enex <sive@web.de>"]
keywords = ["SDL", "window", "graphics", "gui", "react", "dataflow", "ui", "cairo", "2d", "visual", "vector"]
readme = "README.md"
homepage = "https://github.com/enex/rust-gui"
description = "reactiv rust ui  a ReactJS like UI library"

[dependencies]
glutin = "0.0.26"
gl = "0.0.12"

#[dependencies.glutin]
#git = "https://github.com/tomaka/glutin"

[dependencies.nanovg]
git="https://github.com/enex/nanovg-rs"

#[dependencies.gl]
#git = "https://github.com/bjz/gl-rs"
