[package]
name = "rui"
version = "0.0.0"
repository = "https://github.com/enex/rust-gui.git"
license = "LGPL"
authors = ["enex <sive@web.de>"]
keywords = ["SDL", "window", "graphics", "gui", "react", "dataflow", "ui", "cairo", "2d", "visual", "vector"]
readme = "README.md"
homepage = "https://github.com/enex/rust-gui"
description = "react rust ui  a ReactJS like UI library"
#build = "build.rs"

[dependencies]
glutin = "*"
#freetype-rs = "*"
#libc = "*"
#cgmath = "*"

#[dependencies.gfx]
#git = "http://github.com/gfx-rs/gfx-rs"

#[dependencies.gfx_macros]
#git = "http://github.com/gfx-rs/gfx-rs"
#path = "src/gfx_macros"
#plugin = true
#version = "0.1.6"

[dependencies.nanovg]
git="https://github.com/enex/nanovg-rs"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"
