[package]
name = "gui"
version = "0.0.0"
repository = "https://github.com/enex/rust-gui.git"
license = "LGPL"
authors = ["enex <sive@web.de>"]
keywords = ["SDL", "window", "graphics", "gui", "react", "dataflow", "ui", "cairo", "2d", "visual", "vector"]
readme = "README.md"
homepage = "https://github.com/enex/rust-gui"

[dependencies.cairo]
git="https://github.com/enex/rust-cairo"

[dependencies]
sdl2 = "0.0.*"
