[package]
name = "rui"
version = "0.0.0"
repository = "https://github.com/enex/rust-gui.git"
license = "LGPL"
authors = ["enex <sive@web.de>"]
keywords = ["SDL", "window", "graphics", "gui", "react", "dataflow", "ui", "cairo", "2d", "visual", "vector"]
readme = "README.md"
homepage = "https://github.com/enex/rust-gui"
description = "react rust ui  a ReactJS like UI library"

[dependencies.cairo]
git="https://github.com/passcod/rust-cairo"

[dependencies.glutin]
git = "https://github.com/tomaka/glutin"

#[dependencies.nanovg]
#git="https://github.com/KevinKelley/nanovg-rs"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"
