[package]
name = "todo"
version = "0.1.0"
authors = ["Simon Vetter <sive@web.de>"]
description = "a todolist written with rui"

[dependencies.rui]
path = "../../"

[dependencies.rui_azure]
git = "https://github.com/enex/rui-azure"